title: alvarosstsantos
author: Alvaro Soares Sa Teles Santos
email: alvarosstsantos@gmail.com
description: >-
  Engenheiro Químico, Desenvolvedor, Bancário, vivendo intensamente
  o efeito Dunning–Kruger e consumindo literatura de gosto questionável.
baseurl: ""
url: "https://alvarosstsantos.com"
twitter_username: alvarosstsantos
github_username: alvarosstsantos

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: ".."
  date_format: "%d %b %Y"
  show_description: false

sass:
  style: "compressed"
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
